// Package sandbox runs a sequence of shell commands inside an ephemeral
// Docker container: the caller's checkout is mounted read-write at /work,
// the steps run in order (e.g. apply patch, build, test), output streams
// to the caller's logger, and the container is discarded when the run
// ends — including on errors and on context cancellation.
//
// Shipyard uses this for the fix step of a live solve: code generated by
// the AI never runs on the host, and the steps run in a known image
// picked for the repository's language (see ResolveImage). Docker is
// required only for live runs; --dry-run flows never enter this package.
//
// The package shells out to the docker CLI; tests stub the binary on
// PATH, so `go test` needs no Docker daemon.
package sandbox

import (
	"bufio"
	"context"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"regexp"
	"strconv"
	"strings"
	"sync"
	"time"
)

// DockerRequired is the one-line error surfaced when Docker is not
// installed or its daemon is not reachable.
const DockerRequired = "Docker is required for live runs: install Docker or use --dry-run"

// containerMount is where the checkout is mounted inside the container;
// it is also the container's working directory.
const containerMount = "/work"

// markerRe matches the sentinel line the generated container script
// writes to stderr after each step: "__shipyard__ step=N exit=C".
var markerRe = regexp.MustCompile(`^__shipyard__ step=(\d+) exit=(\d+)$`)

// RunSpec configures one sandbox run.
type RunSpec struct {
	// Image names the Docker image explicitly (the --image flag).
	// Empty means resolve it from the repository: the per-repo config
	// (when shipyard.yaml lands) first, then auto-detection from the
	// repository contents (see ResolveImage).
	Image string

	// Workdir is a local checkout. It is mounted read-write at /work
	// inside the container, which is also the container's working
	// directory.
	Workdir string

	// Commands are shell command lines, run in order inside the
	// container — e.g. apply patch, build, test. A non-zero exit code
	// stops the run: the remaining steps are not executed.
	Commands []string

	// Env are extra KEY=VALUE environment variables for the container.
	Env []string

	// Log receives the container's output line by line (stdout and
	// stderr, minus the step sentinels). It may be called from several
	// goroutines, so it must be concurrency-safe. Nil discards output.
	Log func(format string, args ...any)
}

// StepResult reports one step.
type StepResult struct {
	// Command is the shell command line that was run.
	Command string

	// Ran reports whether the step executed. Steps after a failed step
	// did not run.
	Ran bool

	// ExitCode is the step's exit code; it is -1 when the step did not
	// run or its exit code could not be determined.
	ExitCode int
}

// RunResult reports a sandbox run.
type RunResult struct {
	// Image is the image the run used.
	Image string

	// Steps is the per-step outcome, in order.
	Steps []StepResult

	// OK reports whether every step ran and exited zero.
	OK bool
}

// Run executes spec.Commands inside an ephemeral container built on
// spec.Workdir. Container output is streamed to spec.Log line by line;
// per-step exit codes come back in the result, and a failed step is
// reported there, not as an error.
//
// Run returns an error only for infrastructure failures: an invalid
// spec, Docker being missing or unreachable (DockerRequired), the
// container failing to start, or a cancelled context. In every case —
// including errors and cancellation — the container is removed before
// Run returns.
//
// The image must provide /bin/sh.
func Run(ctx context.Context, spec RunSpec) (*RunResult, error) {
	if ctx.Err() != nil {
		return nil, fmt.Errorf("sandbox: run cancelled: %w", ctx.Err())
	}
	if spec.Workdir == "" {
		return nil, errors.New("sandbox: Workdir is required")
	}
	fi, err := os.Stat(spec.Workdir)
	if err != nil {
		return nil, fmt.Errorf("sandbox: workdir %s: %w", spec.Workdir, err)
	}
	if !fi.IsDir() {
		return nil, fmt.Errorf("sandbox: workdir %s is not a directory", spec.Workdir)
	}
	for _, e := range spec.Env {
		if k, _, ok := strings.Cut(e, "="); !ok || k == "" {
			return nil, fmt.Errorf("sandbox: malformed Env entry %q (want KEY=VALUE)", e)
		}
	}

	docker, err := ensureDocker(ctx)
	if err != nil {
		return nil, err
	}

	log := spec.Log
	if log == nil {
		log = func(string, ...any) {}
	}
	image := ResolveImage(spec.Image, spec.Workdir)
	name := containerName()
	log("sandbox: %d step(s) in %s (workdir %s, container %s)", len(spec.Commands), image, spec.Workdir, name)

	res := &RunResult{Image: image, Steps: make([]StepResult, len(spec.Commands))}
	for i, c := range spec.Commands {
		res.Steps[i] = StepResult{Command: c, ExitCode: -1}
	}
	st := &runState{res: res, log: log}

	args := []string{
		"run", "--rm",
		"--name", name,
		"--entrypoint", "/bin/sh",
		"-v", spec.Workdir + ":" + containerMount,
		"-w", containerMount,
	}
	for _, e := range spec.Env {
		args = append(args, "-e", e)
	}
	args = append(args, image, "-c", buildScript(spec.Commands))

	cmd := exec.Command(docker, args...)
	ownProcessGroup(cmd)
	outPipe, err := cmd.StdoutPipe()
	if err != nil {
		return nil, fmt.Errorf("sandbox: preparing run: %w", err)
	}
	errPipe, err := cmd.StderrPipe()
	if err != nil {
		return nil, fmt.Errorf("sandbox: preparing run: %w", err)
	}
	if err := cmd.Start(); err != nil {
		removeContainer(ctx, docker, name)
		return nil, fmt.Errorf("sandbox: starting docker: %w", err)
	}
	go func() {
		<-ctx.Done()
		if ctx.Err() != nil {
			killProcessGroup(cmd)
		}
	}()
	var wg sync.WaitGroup
	wg.Add(2)
	go func() { defer wg.Done(); streamLines(outPipe, st.stdoutLine) }()
	go func() { defer wg.Done(); streamLines(errPipe, st.stderrLine) }()
	waitErr := cmd.Wait()
	wg.Wait()
	removeContainer(ctx, docker, name)

	if ctxErr := ctx.Err(); ctxErr != nil {
		return nil, fmt.Errorf("sandbox: run cancelled: %w", ctxErr)
	}
	code := 0
	var ee *exec.ExitError
	if errors.As(waitErr, &ee) {
		code = ee.ExitCode()
	}
	if code != 0 && st.markers() == 0 {
		// Docker itself failed (bad image, run rejected, ...): no step
		// ran at all.
		msg := "sandbox: docker run failed"
		if tail := st.tailString(); tail != "" {
			msg += ": " + tail
		}
		if waitErr != nil {
			msg += " (" + waitErr.Error() + ")"
		}
		return nil, errors.New(msg)
	}

	res.OK = true
	for _, s := range res.Steps {
		if !s.Ran || s.ExitCode != 0 {
			res.OK = false
			break
		}
	}
	log("sandbox: run finished (ok=%t)", res.OK)
	return res, nil
}

// ensureDocker verifies that the docker CLI is on PATH and its daemon
// answers. Either failure returns errors.New(DockerRequired) so the
// caller surfaces exactly one clear line.
func ensureDocker(ctx context.Context) (string, error) {
	bin, err := exec.LookPath("docker")
	if err != nil {
		return "", errors.New(DockerRequired)
	}
	cmd := exec.CommandContext(ctx, bin, "info")
	cmd.Stdout, cmd.Stderr = io.Discard, io.Discard
	if err := cmd.Run(); err != nil {
		return "", errors.New(DockerRequired)
	}
	return bin, nil
}

// removeContainer force-removes the container by name, best effort: with
// --rm the daemon already removed it when it exited, so a clean exit
// makes this a no-op. The call ignores the caller's cancellation
// (context.WithoutCancel) so cleanup still happens when the run was
// cancelled or errored.
func removeContainer(ctx context.Context, docker, name string) {
	cctx, cancel := context.WithTimeout(context.WithoutCancel(ctx), 10*time.Second)
	defer cancel()
	cmd := exec.CommandContext(cctx, docker, "rm", "-f", name)
	cmd.Stdout, cmd.Stderr = io.Discard, io.Discard
	_ = cmd.Run()
}

// runState collects the per-step exit codes and the trailing stderr for
// error messages while the output pumps run.
type runState struct {
	mu          sync.Mutex
	res         *RunResult
	log         func(format string, args ...any)
	markerCount int
	tail        []string
}

// stdoutLine forwards a stdout line to the logger.
func (s *runState) stdoutLine(line string) {
	if line == "" {
		return
	}
	s.log("%s", line)
}

// stderrLine records a step sentinel and forwards everything else.
func (s *runState) stderrLine(line string) {
	if m := markerRe.FindStringSubmatch(line); m != nil {
		i, _ := strconv.Atoi(m[1])
		code, _ := strconv.Atoi(m[2])
		s.mu.Lock()
		if i >= 0 && i < len(s.res.Steps) {
			s.res.Steps[i].Ran = true
			s.res.Steps[i].ExitCode = code
			s.markerCount++
		}
		s.mu.Unlock()
		return
	}
	if line == "" {
		return
	}
	s.mu.Lock()
	s.tail = append(s.tail, line)
	if len(s.tail) > 32 {
		s.tail = s.tail[len(s.tail)-32:]
	}
	s.mu.Unlock()
	s.log("%s", line)
}

func (s *runState) markers() int {
	s.mu.Lock()
	defer s.mu.Unlock()
	return s.markerCount
}

func (s *runState) tailString() string {
	s.mu.Lock()
	defer s.mu.Unlock()
	return strings.Join(s.tail, " ")
}

// streamLines forwards the lines of r to emit until EOF. A trailing
// partial line without a newline is still delivered.
func streamLines(r io.Reader, emit func(string)) {
	br := bufio.NewReader(r)
	for {
		line, err := br.ReadString('\n')
		emit(strings.TrimSuffix(line, "\n"))
		if err != nil {
			return
		}
	}
}

// buildScript renders the steps as one POSIX shell program: each step
// runs in its own shell, its exit code is echoed to stderr as a
// sentinel line the host parses, and a non-zero code ends the run (the
// remaining steps are skipped).
func buildScript(commands []string) string {
	var b strings.Builder
	b.WriteString("ec=0\n")
	for i, c := range commands {
		fmt.Fprintf(&b, "sh -c %s\n", shQuote(c))
		b.WriteString("ec=$?\n")
		fmt.Fprintf(&b, "printf '__shipyard__ step=%d exit=%%s\\n' \"$ec\" >&2\n", i)
		b.WriteString("[ \"$ec\" -eq 0 ] || exit \"$ec\"\n")
	}
	return b.String()
}

// shQuote wraps s in single quotes so it can be embedded in a shell
// command line unchanged.
func shQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// containerName returns a unique container name for one run.
func containerName() string {
	return fmt.Sprintf("shipyard-sbx-%d-%d", os.Getpid(), time.Now().UnixNano())
}
